name: Continuous Integration (CI)

on:
  push:
  pull_request:

jobs:
  run_continuous_integration_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository using a GitHub action
        uses: actions/checkout@v4

      - name: Install uv using a GitHub action
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --extra dev --frozen

      - name: Ruff lint
        run: uv run ruff check src tests

      - name: mypy
        run: uv run mypy src tests

      - name: Pytest
        run: uv run pytest

      - name: Ruff format check
        run: uv run ruff format --check src tests
